name: ielts
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
version: 2.0.0+23

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider:
  flutter_tindercard: ^0.1.8
  firebase_core: 0.4.4
  firebase_analytics:
  firebase_auth: 0.15.4
  cloud_firestore:
  get_it:
  cached_network_image: ^2.0.0
  firebase_messaging: ^6.0.13
  google_fonts:
  google_sign_in:
  basic_utils:
  intl:
  flutter_custom_clippers:
  flutter_emoji: '>= 2.0.0'
  grouped_buttons:
  shared_preferences:
  percent_indicator:
  flutter_tts:
  day_night_switch:
  flutter_fader: ^1.0.0
  custom_switch:
  firebase_crashlytics:
  flutter_screenutil:
  url_launcher:
  flutter_launcher_icons: '^0.7.3'
  just_audio:
  image_picker:
  auto_size_text:
  flutter_tags:
  flutter_inapp_purchase:
  admob_flutter:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reading.jpg
    - assets/writing.jpg
    - assets/listening.jpeg
    - assets/speaking.jpg
    - assets/googlelogo.jpg
    - assets/giphy.gif
    - assets/quiz.png
    - assets/pushing.png
    - assets/sucess.png
    - assets/swipe.jpeg
    - assets/transparent.gif
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-BoldItalic.ttf
        - asset: assets/Montserrat-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
